# .streamlit/secrets.toml
# Replace placeholders with your actual keys

GOOGLE_API_KEY="AIzaSyCjDLiquCFpnghpMEzId5UfP3wq1OogRRs"
NOTION_API_KEY="YOUR_NOTION_INTEGRATION_TOKEN_HERE"
NOTION_DATABASE_ID="YOUR_NOTION_DATABASE_ID_HERE" 